#!/bin/sh

case "${1}" in
   start)
      echo -n "Starting gopherwink..." 
      nohup /root/gopherwink &
      /usr/sbin/set_rgb 255 0 255 
      ;;

   stop)
      echo -n "Stopping gopherwink..."
      killall gopherwink
      ;;

   restart)
      ${0} stop
      sleep 1
      ${0} start
      ;;

   *)
      echo "Usage: $0 [start|stop|restart]"
      ;;
esac
